 DC.B "KONEY PRESENTS: RUSTEATER 178 BPM INDUSTRIAL HARDCORE AMIGA 40K INTRO * "
 DC.B "A TRIBUTE TO  TETSUO  BY SHINIA TSUKAMOTO "
 DC.B "THIS TRACK WAS COMPOSED IN 1998 ON OCTAMED SS AND PUBLISHED IN 2000 ON KONEY REC. .MED ASM PLAYROUTINES ARE USED TO PLAYBACK MUSIC "
 DC.B "GREETINGZ TIME: RAMON, SUBI, VISIONVORTEX, MAZE, DSR, GUY ON POUET, HEDGEHOG. "
 DC.B ""
 DC.L $AAAAAAAA
 EVEN
